/**
 * AttendanceService — clock in/out, breaks, attendance calculation and the
 * calendar/monthly/report/dashboard reads.
 *
 * Business rules (all enforced server-side):
 *   1. Timestamps are always generated by the server — never trusted from the
 *      client.
 *   2. One attendance record per employee per date (unique key).
 *   3. Clock-out requires a clock-in; multiple clock-ins/outs are rejected.
 *   4. Day off / holiday / approved leave do not require (or allow) clock-in.
 *   5. Late / early-leave / under-time / overtime are computed here from the
 *      employee's schedule, never on the client.
 *   6. Approved leave overrides normal attendance; holidays override too.
 */
import type { AttendanceRepository } from '../repositories/attendanceRepository';
import type { HolidayRepository } from '../repositories/holidayRepository';
import type { LeaveRequestRepository } from '../repositories/leaveRequestRepository';
import type { UserRepository } from '../repositories/userRepository';
import type { WorkScheduleRepository } from '../repositories/workScheduleRepository';
import { redisClient } from '../cache/redisClient';
import { badRequest } from '../utils/errors.utils';
import { WorkScheduleService } from './WorkSchedule.service';
import type {
  AttendanceDashboard,
  AttendanceDay,
  AttendanceMonthSummary,
  AttendanceRecordRow,
  AttendanceStatus,
  EmployeeAttendanceRow,
  OvertimeRecordRow,
  WorkScheduleRow,
} from '../types';

/** Real-time event published by the attendance feature (WS + Redis). */
export interface AttendanceEventPayload {
  type:
    | 'attendance:clocked_in'
    | 'attendance:clocked_out'
    | 'attendance:status_changed'
    | 'attendance:break_started'
    | 'attendance:break_ended';
  data: Record<string, unknown>;
  companyId: number;
  /** When set, only these users receive the event (otherwise the company). */
  userIds?: number[];
}

export interface AttendanceEventPublisher {
  publish(payload: AttendanceEventPayload): void;
}

// ---------------------------------------------------------------------------
// Time helpers (server-local time)
// ---------------------------------------------------------------------------

/** Local YYYY-MM-DD for a Date. */
const localDateStr = (d: Date): string => {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
};

/** Minutes since midnight for a 'HH:MM[:SS]' string. */
const timeToMinutes = (t: string | null | undefined): number | null => {
  if (!t) return null;
  const [h, m] = t.split(':').map(Number);
  if (Number.isNaN(h) || Number.isNaN(m)) return null;
  return h * 60 + m;
};

/** Minutes since midnight (local) for a Date. */
const dateToMinutes = (d: Date): number => d.getHours() * 60 + d.getMinutes();

/** Format minutes as "8h 30m". */
export const formatMinutes = (minutes: number): string => {
  const abs = Math.max(0, Math.round(minutes));
  const h = Math.floor(abs / 60);
  const m = abs % 60;
  if (h === 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
};

/** Format a Date as 'HH:MM AM/PM'. */
export const formatClockTime = (d: Date | string | null): string | null => {
  if (!d) return null;
  const date = typeof d === 'string' ? new Date(d) : d;
  if (Number.isNaN(date.getTime())) return String(d);
  let h = date.getHours();
  const ampm = h >= 12 ? 'PM' : 'AM';
  h = h % 12 || 12;
  return `${String(h).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')} ${ampm}`;
};

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------
export class AttendanceService {
  constructor(
    private attendanceRepository: AttendanceRepository,
    private workScheduleService: WorkScheduleService,
    private workScheduleRepository: WorkScheduleRepository,
    private holidayRepository: HolidayRepository,
    private leaveRequestRepository: LeaveRequestRepository,
    private userRepository: UserRepository,
    private events: AttendanceEventPublisher,
  ) {}

  // =========================================================================
  // Clock in / out / breaks
  // =========================================================================

  async clockIn(employeeId: number): Promise<AttendanceRecordRow> {
    const user = await this.userRepository.findById(employeeId);
    if (!user)    throw badRequest('Employee not found');
    if (!user.is_active)    throw badRequest('Account is disabled');

    const now = new Date();
    const today = localDateStr(now);

    const schedule = await this.workScheduleService.getForWeekday(employeeId, now.getDay());

    // Holiday / leave / day off guard — none of these allow clock-in.
    const holiday = await this.holidayRepository.findByDate(today);
    if (holiday)    throw badRequest('Today is a public holiday — no clock-in required');

    const leave = await this.leaveRequestRepository.findApprovedOverlap(employeeId, today, today);
    if (leave.length > 0)    throw badRequest('You are on approved leave today');

    if (!schedule.is_working_day) {
      throw badRequest('Today is a day off — no clock-in required');
    }

    const existing = await this.attendanceRepository.findByEmployeeAndDate(employeeId, today);
    if (existing) {
      if (existing.clock_in)    throw badRequest('You have already clocked in today');
      // Stale record without clock-in (e.g. created by leave approval) — reuse it.
    }

    const clockInTime = now;
    const scheduledStartMin = timeToMinutes(schedule.start_time);
    const lateMinutes = scheduledStartMin !== null
      ? Math.max(0, dateToMinutes(clockInTime) - scheduledStartMin)
      : 0;
    const status: AttendanceStatus = lateMinutes > 0 ? 'late' : 'present';

    const recordId = existing
      ? existing.id
      : await this.attendanceRepository.create({
          employee_id: employeeId,
          date: today,
          scheduled_start: schedule.start_time,
          scheduled_end: schedule.end_time,
          required_work_minutes: schedule.required_work_minutes,
        });

    await this.attendanceRepository.update(recordId, {
      clock_in: clockInTime,
      late_minutes: lateMinutes,
      status,
    });

    const record = await this.attendanceRepository.findById(recordId);
    if (!record)    throw badRequest('Could not load attendance record');

    this.invalidateDashboard(user.company_id ?? 0, today);
    this.events.publish({
      type: 'attendance:clocked_in',
      companyId: user.company_id ?? 0,
      userIds: [employeeId],
      data: { record: this.serializeRecord(record), date: today },
    });
    this.events.publish({
      type: 'attendance:status_changed',
      companyId: user.company_id ?? 0,
      data: { employeeId, date: today, status, record: this.serializeRecord(record) },
    });
    return record;
  }

  async clockOut(employeeId: number): Promise<AttendanceRecordRow> {
    const user = await this.userRepository.findById(employeeId);
    if (!user)    throw badRequest('Employee not found');

    const now = new Date();
    const today = localDateStr(now);

    const record = await this.attendanceRepository.findByEmployeeAndDate(employeeId, today);
    if (!record || !record.clock_in) {
      throw badRequest('You must clock in before clocking out');
    }
    if (record.clock_out) {
      throw badRequest('You have already clocked out today');
    }

    const runningBreak = await this.attendanceRepository.findRunningBreak(record.id);
    if (runningBreak) {
      throw badRequest('You have a running break — end it before clocking out');
    }

    const clockIn = new Date(String(record.clock_in));
    const clockOut = now;

    // Break time: actual recorded breaks when present, otherwise the
    // scheduled break (the standard 60-minute lunch).
    const actualBreaks = await this.attendanceRepository.totalBreakMinutes(record.id);
    const breakTotal = actualBreaks > 0
      ? actualBreaks
      : (record.scheduled_start && record.scheduled_end ? await this.scheduledBreakMinutes(employeeId, now.getDay()) : 0);

    const rawMinutes = Math.max(0, (clockOut.getTime() - clockIn.getTime()) / 60000 - breakTotal);
    const totalWorkMinutes = Math.round(rawMinutes);

    const scheduledStartMin = timeToMinutes(record.scheduled_start);
    const scheduledEndMin = timeToMinutes(record.scheduled_end);
    const lateMinutes = scheduledStartMin !== null
      ? Math.max(0, dateToMinutes(clockIn) - scheduledStartMin)
      : 0;
    const earlyLeaveMinutes = scheduledEndMin !== null
      ? Math.max(0, scheduledEndMin - dateToMinutes(clockOut))
      : 0;

    const required = record.required_work_minutes || 480;
    const overtimeMinutes = Math.max(0, totalWorkMinutes - required);
    const underTimeMinutes = Math.max(0, required - totalWorkMinutes);

    let status: AttendanceStatus = 'present';
    if (lateMinutes > 0) status = 'late';
    else if (earlyLeaveMinutes > 0) status = 'early_leave';
    else if (underTimeMinutes > 0) status = 'under_time';
    else if (overtimeMinutes > 0) status = 'overtime';

    await this.attendanceRepository.update(record.id, {
      clock_out: clockOut,
      total_work_minutes: totalWorkMinutes,
      late_minutes: lateMinutes,
      early_leave_minutes: earlyLeaveMinutes,
      overtime_minutes: overtimeMinutes,
      status,
    });

    const updated = await this.attendanceRepository.findById(record.id);
    if (!updated)    throw badRequest('Could not load attendance record');

    this.invalidateDashboard(user.company_id ?? 0, today);
    this.events.publish({
      type: 'attendance:clocked_out',
      companyId: user.company_id ?? 0,
      userIds: [employeeId],
      data: { record: this.serializeRecord(updated), date: today },
    });
    this.events.publish({
      type: 'attendance:status_changed',
      companyId: user.company_id ?? 0,
      data: { employeeId, date: today, status, record: this.serializeRecord(updated) },
    });
    return updated;
  }

  async startBreak(employeeId: number): Promise<{ breakId: number; startedAt: Date }> {
    const user = await this.userRepository.findById(employeeId);
    if (!user)    throw badRequest('Employee not found');

    const today = localDateStr(new Date());
    const record = await this.attendanceRepository.findByEmployeeAndDate(employeeId, today);
    if (!record || !record.clock_in)    throw badRequest('You must clock in before starting a break');
    if (record.clock_out)    throw badRequest('You have already clocked out');

    const running = await this.attendanceRepository.findRunningBreak(record.id);
    if (running)    throw badRequest('You already have a running break');

    const now = new Date();
    const breakId = await this.attendanceRepository.createBreak(record.id, now);

    this.invalidateDashboard(user.company_id ?? 0, today);
    this.events.publish({
      type: 'attendance:break_started',
      companyId: user.company_id ?? 0,
      userIds: [employeeId],
      data: { breakId, attendanceId: record.id, startedAt: now.toISOString(), date: today },
    });
    return { breakId, startedAt: now };
  }

  async endBreak(employeeId: number): Promise<{ breakId: number; durationMinutes: number }> {
    const user = await this.userRepository.findById(employeeId);
    if (!user)    throw badRequest('Employee not found');

    const today = localDateStr(new Date());
    const record = await this.attendanceRepository.findByEmployeeAndDate(employeeId, today);
    if (!record || !record.clock_in)    throw badRequest('You must clock in before ending a break');
    if (record.clock_out)    throw badRequest('You have already clocked out');

    const running = await this.attendanceRepository.findRunningBreak(record.id);
    if (!running)    throw badRequest('No running break to end');

    const now = new Date();
    const duration = Math.max(0, Math.round((now.getTime() - new Date(String(running.break_start)).getTime()) / 60000));
    await this.attendanceRepository.endBreak(running.id, now, duration);

    this.invalidateDashboard(user.company_id ?? 0, today);
    this.events.publish({
      type: 'attendance:break_ended',
      companyId: user.company_id ?? 0,
      userIds: [employeeId],
      data: { breakId: running.id, attendanceId: record.id, durationMinutes: duration, date: today },
    });
    return { breakId: running.id, durationMinutes: duration };
  }

  /** Drop the cached company dashboard for a date (fire-and-forget). */
  private invalidateDashboard(companyId: number, date: string): void {
    void redisClient.del(`attendance:dashboard:${companyId}:${date}`).catch(() => {});
  }

  private async scheduledBreakMinutes(employeeId: number, dayOfWeek: number): Promise<number> {
    const schedule = await this.workScheduleService.getForWeekday(employeeId, dayOfWeek);
    return schedule.break_minutes || 60;
  }

  // =========================================================================
  // Employee calendar reads
  // =========================================================================

  /** Today's attendance + schedule card for the employee. */
  async getToday(employeeId: number): Promise<AttendanceDay> {
    const now = new Date();
    const today = localDateStr(now);
    const [schedule, holiday, leave] = await Promise.all([
      this.workScheduleService.getForWeekday(employeeId, now.getDay()),
      this.holidayRepository.findByDate(today),
      this.leaveRequestRepository.findApprovedOverlap(employeeId, today, today),
    ]);
    const record = await this.attendanceRepository.findByEmployeeAndDate(employeeId, today);
    const day = this.buildDay(employeeId, today, now.getDay(), schedule, holiday, leave.length > 0, record, true);
    if (record && record.clock_in && !record.clock_out) {
      day.running_break = !!(await this.attendanceRepository.findRunningBreak(record.id));
    } else {
      day.running_break = false;
    }
    return day;
  }

  /** One month of calendar days + a roll-up summary. */
  async getMonth(
    employeeId: number,
    year: number,
    month: number, // 1-based
  ): Promise<{ days: AttendanceDay[]; summary: AttendanceMonthSummary }> {
    const start = `${year}-${String(month).padStart(2, '0')}-01`;
    const daysInMonth = new Date(year, month, 0).getDate();
    const end = `${year}-${String(month).padStart(2, '0')}-${String(daysInMonth).padStart(2, '0')}`;

    const [schedules, holidays, leaves, records] = await Promise.all([
      this.workScheduleService.getForEmployee(employeeId),
      this.holidayRepository.findBetween(start, end),
      this.leaveRequestRepository.findApprovedOverlap(employeeId, start, end),
      this.attendanceRepository.findByEmployeeBetween(employeeId, start, end),
    ]);

    const holidayByDate = new Map(holidays.map((h) => [h.date, h]));
    const leaveDates = new Set<string>();
    for (const l of leaves) {
      let d = new Date(`${l.start_date}T00:00:00`);
      const endDate = new Date(`${l.end_date}T00:00:00`);
      while (d <= endDate) {
        leaveDates.add(localDateStr(d));
        d.setDate(d.getDate() + 1);
      }
    }
    const recordByDate = new Map(records.map((r) => [r.date, r]));
    const scheduleByDay = new Map(schedules.map((s) => [s.day_of_week, s]));
    const todayStr = localDateStr(new Date());

    const days: AttendanceDay[] = [];
    for (let day = 1; day <= daysInMonth; day++) {
      const date = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      const dow = new Date(year, month - 1, day).getDay();
      const schedule = scheduleByDay.get(dow);
      days.push(this.buildDay(
        employeeId,
        date,
        dow,
        schedule ?? null,
        holidayByDate.get(date) ?? null,
        leaveDates.has(date),
        recordByDate.get(date) ?? null,
        date === todayStr,
      ));
    }

    return { days, summary: this.summarizeDays(days, year, month) };
  }

  // =========================================================================
  // Overtime requests
  // =========================================================================

  /** Employee submits an overtime request for a specific work date. */
  async requestOvertime(
    employeeId: number,
    data: { date: string; minutes: number; reason?: string },
  ): Promise<OvertimeRecordRow> {
    const user = await this.userRepository.findById(employeeId);
    if (!user)    throw badRequest('Employee not found');
    if (!/^\d{4}-\d{2}-\d{2}$/.test(data.date)) {
      throw badRequest('Date must use YYYY-MM-DD format');
    }
    const minutes = Math.round(Number(data.minutes));
    if (!Number.isFinite(minutes) || minutes <= 0) {
      throw badRequest('Overtime minutes must be a positive number');
    }
    if (minutes > 1440) {
      throw badRequest('Overtime minutes cannot exceed 24 hours (1440)');
    }

    // Link to the day's attendance record when one exists, and reject a
    // duplicate pending request for the same date.
    const record = await this.attendanceRepository.findByEmployeeAndDate(employeeId, data.date);
    const existing = await this.attendanceRepository.findOvertimeByEmployeeAndDate(employeeId, data.date);
    if (existing.some((o) => o.status === 'pending')) {
      throw badRequest('You already have a pending overtime request for this date');
    }

    const id = await this.attendanceRepository.createOvertime({
      employee_id: employeeId,
      date: data.date,
      attendance_id: record ? record.id : null,
      minutes,
      reason: data.reason?.trim() || null,
    });
    const created = await this.attendanceRepository.findOvertimeById(id);
    if (!created)    throw badRequest('Could not create overtime request');
    return created;
  }

  /** Employees see their own overtime requests; managers see the company's. */
  async listOvertime(
    companyId: number,
    employeeId: number,
    isManager: boolean,
  ): Promise<OvertimeRecordRow[]> {
    return isManager
      ? this.attendanceRepository.findOvertimeByCompany(companyId)
      : this.attendanceRepository.findOvertimeByEmployee(employeeId);
  }

  /** Manager approves / rejects a pending overtime request. */
  async setOvertimeStatus(
    id: number,
    status: 'approved' | 'rejected',
    approverId: number,
  ): Promise<OvertimeRecordRow> {
    const existing = await this.attendanceRepository.findOvertimeById(id);
    if (!existing)    throw badRequest('Overtime request not found');
    if (existing.status !== 'pending') {
      throw badRequest('Only pending overtime requests can be approved or rejected');
    }
    await this.attendanceRepository.setOvertimeStatus(id, status, approverId);
    const updated = await this.attendanceRepository.findOvertimeById(id);
    if (!updated)    throw badRequest('Could not update overtime request');
    return updated;
  }

  // =========================================================================
  // Manager reads
  // =========================================================================

  /** Employee × day attendance table for the manager dashboard. */
  async getEmployees(
    companyId: number,
    opts: { year: number; month: number; departmentId?: number; status?: string },
  ): Promise<EmployeeAttendanceRow[]> {
    const { year, month } = opts;
    const start = `${year}-${String(month).padStart(2, '0')}-01`;
    const daysInMonth = new Date(year, month, 0).getDate();
    const end = `${year}-${String(month).padStart(2, '0')}-${String(daysInMonth).padStart(2, '0')}`;

    const [users, records, holidays, leaves, schedules] = await Promise.all([
      this.userRepository.findAll({ companyId, limit: 10000, page: 1 }),
      this.attendanceRepository.findByCompanyBetween(companyId, start, end),
      this.holidayRepository.findBetween(start, end),
      this.leaveRequestRepository.findByCompany(companyId, 'approved'),
      this.workScheduleRepository.findAllByCompany(companyId),
    ]);

    const holidayByDate = new Map(holidays.map((h) => [h.date, h]));
    const recordsByEmployee = new Map<number, Map<string, AttendanceRecordRow>>();
    for (const r of records) {
      if (!recordsByEmployee.has(r.employee_id)) recordsByEmployee.set(r.employee_id, new Map());
      recordsByEmployee.get(r.employee_id)!.set(r.date, r);
    }
    const leaveByEmployee = new Map<number, Set<string>>();
    for (const l of leaves) {
      if (!leaveByEmployee.has(l.employee_id)) leaveByEmployee.set(l.employee_id, new Set());
      const set = leaveByEmployee.get(l.employee_id)!;
      let d = new Date(`${l.start_date}T00:00:00`);
      const endDate = new Date(`${l.end_date}T00:00:00`);
      while (d <= endDate) {
        set.add(localDateStr(d));
        d.setDate(d.getDate() + 1);
      }
    }
    const scheduleByEmployee = new Map<number, Map<number, WorkScheduleRow>>();
    for (const s of schedules) {
      if (!scheduleByEmployee.has(s.employee_id)) scheduleByEmployee.set(s.employee_id, new Map());
      scheduleByEmployee.get(s.employee_id)!.set(s.day_of_week, s);
    }

    const todayStr = localDateStr(new Date());
    const rows: EmployeeAttendanceRow[] = [];

    // Employees whose schedule has not been materialized yet default to
    // Mon–Fri 08:00–17:00 — materialize rows so every day is classified
    // correctly (a missing schedule must not read as "day off").
    const activeUsers = users.filter((u) => u.is_active);
    for (const u of activeUsers) {
      if (!scheduleByEmployee.has(u.id)) {
        await this.workScheduleService.ensureSchedule(u.id);
        const fresh = await this.workScheduleRepository.findByEmployee(u.id);
        scheduleByEmployee.set(u.id, new Map(fresh.map((s) => [s.day_of_week, s])));
      }
    }

    for (const u of activeUsers) {
      if (opts.departmentId && Number(u.department_id) !== Number(opts.departmentId)) continue;

      const empRecords = recordsByEmployee.get(u.id) || new Map();
      const empLeaves = leaveByEmployee.get(u.id) || new Set();
      const empSchedules = scheduleByEmployee.get(u.id) || new Map();

      const days: AttendanceDay[] = [];
      for (let day = 1; day <= daysInMonth; day++) {
        const date = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        const dow = new Date(year, month - 1, day).getDay();
        const schedule = empSchedules.get(dow) ?? null;
        days.push(this.buildDay(
          u.id,
          date,
          dow,
          schedule,
          holidayByDate.get(date) ?? null,
          empLeaves.has(date),
          empRecords.get(date) ?? null,
          date === todayStr,
        ));
      }

      const summary = this.summarizeDays(days, year, month);
      // Status filter: keep employees who have at least one matching day in
      // the month (e.g. show everyone who had a "late" day).
      if (opts.status && !days.some((d) => d.status === opts.status)) continue;

      rows.push({
        employee_id: u.id,
        first_name: u.first_name,
        last_name: u.last_name,
        department_id: u.department_id ?? null,
        department_name: null, // filled below
        days,
        summary,
      });
    }

    // Attach department names in one pass.
    if (rows.length > 0) {
      const deptIds = Array.from(new Set(rows.map((r) => r.department_id).filter((d): d is number => d !== null)));
      const names = await this.departmentNames(deptIds);
      for (const r of rows) {
        r.department_name = r.department_id !== null ? names.get(r.department_id) ?? null : null;
      }
    }

    return rows;
  }

  /** One employee's attendance calendar + summary (manager drill-down). */
  async getEmployeeDetail(
    companyId: number,
    employeeId: number,
    year: number,
    month: number,
  ): Promise<{ employee: { id: number; first_name: string; last_name: string; department_id: number | null; department_name: string | null }; days: AttendanceDay[]; summary: AttendanceMonthSummary }> {
    const user = await this.userRepository.findById(employeeId);
    if (!user || Number(user.company_id) !== Number(companyId)) {
      throw badRequest('Employee not found in this company');
    }
    const { days, summary } = await this.getMonth(employeeId, year, month);
    const departmentName = user.department_id
      ? (await this.departmentNames([user.department_id])).get(user.department_id) ?? null
      : null;
    return {
      employee: {
        id: user.id,
        first_name: user.first_name,
        last_name: user.last_name,
        department_id: user.department_id ?? null,
        department_name: departmentName,
      },
      days,
      summary,
    };
  }

  /** Per-employee monthly summary report. */
  async getReport(
    companyId: number,
    year: number,
    month: number,
  ): Promise<Array<EmployeeAttendanceRow['summary'] & { employee_id: number; first_name: string; last_name: string; department_name: string | null }>> {
    const rows = await this.getEmployees(companyId, { year, month });
    return rows.map((r) => ({
      employee_id: r.employee_id,
      first_name: r.first_name,
      last_name: r.last_name,
      department_name: r.department_name,
      ...r.summary,
    }));
  }

  /** Today's company dashboard (manager). */
  async getDashboard(companyId: number, dateStr?: string): Promise<AttendanceDashboard> {
    const now = new Date();
    const date = dateStr || localDateStr(now);
    const cacheKey = `attendance:dashboard:${companyId}:${date}`;
    const cached = await redisClient.get(cacheKey);
    if (cached) {
      try {
        return JSON.parse(cached) as AttendanceDashboard;
      } catch {
        // malformed cache entry — recompute
      }
    }
    const dow = new Date(`${date}T00:00:00`).getDay();

    const [users, records, holiday, leaves] = await Promise.all([
      this.userRepository.findAll({ companyId, limit: 10000, page: 1 }),
      this.attendanceRepository.findByCompanyBetween(companyId, date, date),
      this.holidayRepository.findByDate(date),
      this.leaveRequestRepository.findByCompany(companyId, 'approved'),
    ]);

    const activeUsers = users.filter((u) => u.is_active);
    const recordByEmployee = new Map(records.map((r) => [r.employee_id, r]));
    const leaveEmployees = new Set<number>();
    for (const l of leaves) {
      if (l.start_date <= date && l.end_date >= date) leaveEmployees.add(l.employee_id);
    }

    const dashboard: AttendanceDashboard = {
      date,
      total_employees: activeUsers.length,
      present: 0,
      late: 0,
      absent: 0,
      on_leave: 0,
      day_off: 0,
      holiday: 0,
      not_started: 0,
      currently_working: 0,
      on_break: 0,
    };

    if (holiday) {
      dashboard.holiday = activeUsers.length;
      return dashboard;
    }

    const nowMinutes = dateToMinutes(now);
    for (const u of activeUsers) {
      if (leaveEmployees.has(u.id)) {
        dashboard.on_leave += 1;
        continue;
      }
      const schedule = await this.workScheduleService.getForWeekday(u.id, dow);
      if (!schedule.is_working_day) {
        dashboard.day_off += 1;
        continue;
      }
      const record = recordByEmployee.get(u.id);
      if (record && record.clock_in) {
        const status = record.status;
        if (status === 'late') dashboard.late += 1;
        else dashboard.present += 1;
        const runningBreak = await this.attendanceRepository.findRunningBreak(record.id);
        if (record.clock_out) {
          // finished for the day — still counts as present
        } else if (runningBreak) {
          dashboard.on_break += 1;
          dashboard.currently_working += 1;
        } else {
          dashboard.currently_working += 1;
        }
      } else {
        const endMin = timeToMinutes(schedule.end_time);
        if (endMin !== null && nowMinutes > endMin) dashboard.absent += 1;
        else dashboard.not_started += 1;
      }
    }

    // Short-TTL cache (10s) — invalidated by clock/break events so the
    // manager dashboard stays fresh without hammering MySQL on every poll.
    void redisClient.set(cacheKey, JSON.stringify(dashboard), 10).catch(() => {});
    return dashboard;
  }

  // =========================================================================
  // Internals
  // =========================================================================

  private async departmentNames(ids: number[]): Promise<Map<number, string>> {
    if (ids.length === 0) return new Map();
    const rows = await this.attendanceRepository.findDepartmentNames(ids);
    return new Map(rows.map((r) => [r.id, r.name]));
  }

  /**
   * Build one calendar day by merging schedule + holiday + leave + record.
   * Status is computed here (the backend owns the rules).
   */
  private buildDay(
    employeeId: number,
    date: string,
    dayOfWeek: number,
    schedule: WorkScheduleRow | null,
    holiday: { id: number; name: string; date: string; description: string | null } | null,
    onLeave: boolean,
    record: AttendanceRecordRow | null,
    isToday: boolean,
  ): AttendanceDay {
    const todayStr = localDateStr(new Date());

    let status: AttendanceDay['status'] = null;
    if (holiday) status = 'holiday';
    else if (onLeave) status = 'leave';
    else if (!schedule || !schedule.is_working_day) status = 'day_off';
    else if (record && record.clock_in) {
      status = record.status;
      // A day with overtime or under-time is still counted by its computed
      // status; nothing extra to do here.
    } else if (date < todayStr) status = 'absent';
    else if (isToday) status = 'not_started';

    // Holidays override the schedule entirely — required working time is 0h.
    const required = holiday ? 0 : ((schedule?.is_working_day ? schedule.required_work_minutes : 0) || 0);
    let totalWork = record?.total_work_minutes ?? null;
    let underTime = 0;
    let overtime = record?.overtime_minutes ?? 0;

    // Live in-progress values for today (clocked in but not out).
    if (isToday && record && record.clock_in && !record.clock_out) {
      const clockIn = new Date(String(record.clock_in));
      const raw = Math.max(0, (Date.now() - clockIn.getTime()) / 60000 - (schedule?.break_minutes || 60));
      totalWork = Math.round(raw);
      underTime = Math.max(0, required - totalWork);
      overtime = Math.max(0, totalWork - required);
    } else if (record && record.clock_out) {
      const r = record as AttendanceRecordRow;
      underTime = Math.max(0, required - (r.total_work_minutes ?? 0));
      overtime = r.overtime_minutes ?? 0;
    }

    return {
      date,
      day_of_week: dayOfWeek,
      is_working_day: !!schedule?.is_working_day,
      is_day_off: !schedule?.is_working_day,
      is_holiday: !!holiday,
      holiday_name: holiday?.name ?? null,
      scheduled_start: schedule?.is_working_day ? (schedule.start_time ?? null) : null,
      scheduled_end: schedule?.is_working_day ? (schedule.end_time ?? null) : null,
      break_minutes: schedule?.break_minutes ?? 0,
      required_work_minutes: required,
      clock_in: record?.clock_in ? new Date(record.clock_in).toISOString() : null,
      clock_out: record?.clock_out ? new Date(record.clock_out).toISOString() : null,
      total_work_minutes: totalWork,
      late_minutes: record?.late_minutes ?? 0,
      early_leave_minutes: record?.early_leave_minutes ?? 0,
      under_time_minutes: underTime,
      overtime_minutes: overtime,
      status,
    };
  }

  private summarizeDays(days: AttendanceDay[], year: number, month: number): AttendanceMonthSummary {
    const summary: AttendanceMonthSummary = {
      year,
      month,
      working_days: 0,
      present: 0,
      late: 0,
      absent: 0,
      leave: 0,
      day_off: 0,
      holidays: 0,
      required_minutes: 0,
      actual_minutes: 0,
      under_time_minutes: 0,
      overtime_minutes: 0,
      attendance_rate: null,
    };

    for (const d of days) {
      if (d.status === 'holiday') {
        summary.holidays += 1;
        continue;
      }
      if (d.status === 'day_off') {
        summary.day_off += 1;
        continue;
      }
      if (d.status === 'leave') {
        summary.leave += 1;
        // Approved leave is a working day contractually — required hours are
        // still owed/planned, but leave is never under-time or absence.
        summary.required_minutes += d.required_work_minutes;
        continue;
      }
      if (d.is_working_day) {
        summary.working_days += 1;
        summary.required_minutes += d.required_work_minutes;
        summary.actual_minutes += d.total_work_minutes ?? 0;
        summary.overtime_minutes += d.overtime_minutes;
        switch (d.status) {
          case 'present': summary.present += 1; break;
          case 'late': summary.late += 1; break;
          case 'early_leave': summary.present += 1; break;
          case 'under_time': summary.present += 1; break;
          case 'overtime': summary.present += 1; break;
          case 'absent': summary.absent += 1; break;
          default: break;
        }
        // Under-time counts only completed, attended days (never leave or
        // absence) — a finished day short of its required minutes.
        if (d.clock_out) {
          summary.under_time_minutes += d.under_time_minutes;
        }
      }
    }
    if (summary.working_days > 0) {
      const attended = summary.working_days - summary.absent;
      summary.attendance_rate = Math.round((attended / summary.working_days) * 1000) / 10;
    }
    return summary;
  }

  private serializeRecord(record: AttendanceRecordRow): Record<string, unknown> {
    return {
      id: record.id,
      employee_id: record.employee_id,
      date: record.date,
      scheduled_start: record.scheduled_start,
      scheduled_end: record.scheduled_end,
      required_work_minutes: record.required_work_minutes,
      clock_in: record.clock_in ? new Date(record.clock_in).toISOString() : null,
      clock_out: record.clock_out ? new Date(record.clock_out).toISOString() : null,
      total_work_minutes: record.total_work_minutes,
      late_minutes: record.late_minutes,
      early_leave_minutes: record.early_leave_minutes,
      overtime_minutes: record.overtime_minutes,
      status: record.status,
    };
  }
}
